export interface Book {
    book_id: number,
    title: string,
    description: string,
    category_id: string,
    author: string,
    publication_year:string,
    cover_image:any,
    publisher: string,
    no_of_copy: number,
    available_copy: number,
    issuable_copy: number,
    accession_no: string,
    price: number,
    edition: string,
    shelf_no: number,
    row_no: number,
    type: number,
    booking_duration: any,
    fine: string,
    file: any,
    book_url: any,
    isbn_no:string,
    created_at: string,
    updated_at: string
}